version: '3.5'

services:
    backend:
        container_name: url-shortener-backend
        build: .
        ports:
            - 8080:8080
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - MONGO_URI=mongodb://admin:password@mongodb:27017/
        depends_on:
            - mongodb

    mongodb:
        container_name: url-shortener-db
        image: mongo:focal
        ports:
            - 27017:27017
        restart: always
        volumes:
            - ./database:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
    database:
